title: Gijs van Houutum # your name (or website title) here
logo: "/images/dolomite.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  7+ years of experience as a Computer Vision Engineer building algorithms in the manufacturing industry. 
  Masters degree in Control Theory from Eindhoven University of Technology (the Netherlands), 
  PhD in Machine learning from University of Waterloo (Canada).
  <br><br><br>
  Currently developing data-efficient deep learning solutions, such as Active learning and Adaptive 
  Semi-Supervised Video Object Segmentation. 
  # <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
