title: Gijs van Houutum # your name (or website title) here
logo: "/images/dolomite.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Hi there!

I am Gijs van Houtum, a passionate computer vision software engineer/applied scientist. 
I love to write software, develop new algorithms, create awesome machine learning solutions but above all, 
I like to make stuff work. 

My work for last couple of years has been focused towards creating smart deep learning based 
computer vision algorithms for the manufacturing industry. Quality monitoring has been the main task of these algorithms I built.
The main goal is to help and push the manufacturing industry to Industry 5.0 eventually, using these smart solutions! In the
last 7 years I have helped over 5 different companies with newly developed computer vision solutions.

I am also pursueing a PhD in industrial AI (finished Jan-2024). During my work, I noticed the demand for smart solutions based on 
machine learning with the manufacturing industry. Recurring problems from company to company created a personal vision and interest in 
the creation of data-efficient machine learning solutions. Practical experience with AI has taught me the importance of qualitative datasets
used for training as well as validation. Creating them is however time consuming, difficult and expensive. My PhD is therefore focused on creating
awesome solutions that require less data to be annotated, and adaptive machine learning models, that are task invariant, just as we humans do...

In my spare time I love to write software, restore old motorcycles and cars with my dad, sail the seas. During holidays I like to explore, hike and ski.
Examples of personal project include the creation of a electronic fuel injected (EFI) Puch moped and an algorithmic trading engine for long term investing.
# <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
