title: Gijs van Houtum # your name (or website title) here
logo: "/images/photo_gijs_2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  7+ years of experience as a Computer Vision Software Engineer |  
  Masters degree in Control Theory |
  PhD in Machine learning |
  <br><br>
  Currently developing data-efficient deep learning solutions, such as Active learning and Adaptive 
  Semi-Supervised Video Object Segmentation. 
  <br><br>
  <a href="https://www.linkedin.com/in/gijsvanhoutum/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/pdf/CV1.pdf">View My Curriclum Vitae</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
